application: modular-granite-311
version: 1
runtime: python27
api_version: 1
threadsafe: yes

builtins:
- remote_api: on

inbound_services:
- warmup

libraries:
- name: django
  version: latest

handlers:
- url: /_ah/queue/deferred
  script: djangoappengine.deferred.handler.application
  login: admin

- url: /_ah/stats/.*
  script: djangoappengine.appstats.application

- url: /media/admin
  static_dir: django/contrib/admin/media
  expiration: '0'

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /scripts
  static_dir: media/javascripts

- url: /images
  static_dir: media/images

- url: /styles
  static_dir: media/stylesheets

- url: /blender
  static_dir: media/blender

- url: /fonts
  static_dir: media/fonts

- url: /.*
  script: djangoappengine.main.application
